apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ssl-issuer
  namespace: istio-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: rakesh.pillai@sreyo.com
    #email: neethu.somasekharan@sreyo.com
    privateKeySecretRef:
      name: ssl-issuer
    solvers:
    - dns01:
        cloudflare:
          email: evolve@sreyo.in
          #email: managedorg@sreyo.com
          apiTokenSecretRef:
            name: ssl-secret
            key: api-token